### ISSUE TITLE
Python 3.4.7 not available

### ISSUE THREAD

**Issue by ELind77** [tuvistavie/asdf-python#22]
Hey, I know this is kind of a small thing, but I need 3.4.7 specifically.  I've loved using asdf for python and I'd like to keep using it.  It looks like 3.4.7 is available in pyenv: https://github.com/pyenv/pyenv/releases/tag/v1.1.4  I've tried running `asdf plugin-update --all` but that didn't help.  Is there something else I should do to get new Python versions?

And is there some way to automatically get new versions as they become available?

Eric

**Comment by tuvistavie** [comment]
Hi @ELind77, thank you for reporting.
I am aware of this issue and have been too lazy to fix it :sweat: 
The issue is that I am not automatically updating pyenv, so only
versions available when first using `asdf-python` are available.
A temporary workaround is simply to run

```
cd ~/.asdf/plugins/python/pyenv/ && git pul
``` 

The fix is to update pyenv if it was not updated for a while.
If you would like to send a PR for it I would be very pleased to merge it.
Thank you.

**Comment by algtmatt** [comment]
I've opened a small PR that will do a pull on list-all: https://github.com/tuvistavie/asdf-python/pull/34
