### ISSUE TITLE
shim doesn't work when asdf installed with Homebrew

### ISSUE THREAD

**Issue by dancek** [tuvistavie/asdf-python#23]
Homebrew has a policy that only executables may be installed in `bin/` (I asked and they won't make an exception for asdf). Therefore they install `asdf-exec` to `libexec/private` and thus the asdf-python shim fails.

```
exec $(asdf_dir)/bin/private/asdf-exec python bin/python${short_python_version} "$@"
```

I'm not really sure how this should be fixed, but FYI.

**Comment by tuvistavie** [comment]
Hi, thanks for the heads up.
Actually, I think I added the python shim for I can't remember which version which had only `python2` executable and not `python` executable, or something like this, but I cannot find any trace of such a version, so let's simply remove the `python` shim so that the default shim is generated.
